### PR TITLE
Add ability to start and stop CTF tracing

### PR DESCRIPTION
**Pull request by brudley**

### CODE REVIEW

**Comment by brudley** [comment]
Messed up the order of these reviews, zephyr mods should have been first.

**Review by berendo — CHANGES_REQUESTED** [review]
Sorry to be a PITA on this, but when writing Zephyr code, we need to use their formatting (otherwise unrelated and/or whitespace changes make eventual rebases with upstream really tedious). Could you please reformat with tabs instead of spaces and force-push, so that only the real `diff`s remain?

P.S.: There _is_ a `.clang-format` file in the Zephyr repository, so it can be used for this.

**Comment by brudley** [comment]
Absolutely, my bad!

> On Oct 4, 2022, at 7:36 AM, Berend Ozceri ***@***.***> wrote:
> 
> ﻿
> @berendo requested changes on this pull request.
> 
> Sorry to be a PITA on this, but when writing Zephyr code, we need to use their formatting (otherwise unrelated and/or whitespace changes make eventual rebases with upstream really tedious). Could you please reformat with tabs instead of spaces and force-push, so that only the real diffs remain?
> 
> P.S.: There is a .clang-format file in the Zephyr repository, so it can be used for this.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.

-- 
This communication is the property of Recogni Inc. and its affiliates. This 
email and any attachments may contain private, confidential and privileged 
material for the sole use of the intended recipient. If you are not the 
intended recipient of this message, any use, dissemination, distribution, 
or copying of this communication is strictly prohibited.  If you have 
received this communication in error, please immediately notify the sender 
and permanently delete all copies of this email and any attachments that 
you may have.

**Review by berendo — DISMISSED** [review]
Now that I can see the pattern with the formatting consistent with Zephyr (thank you 🙏), I'm going to beg for forgiveness and make another PITA request, again with an eye toward potential future upstream rebases...

For functions like this where the _entire_ body is now put inside a new `if (...) { ... }` conditional, thereby implicitly creating a `diff` on every line within the body due to additional indentation, it would be less fragile to just insert an early-`return` to the beginning of the function:
```
void sys_trace_k_thread_switched_out(void)
{
	if (!is_sys_trace_active) {
		return;
	}
	...
```
This would really minimize the `diff`s in this PR.

**Comment by brudley** [comment]
Excellent suggestion....this should help quite a bit.

**Review by sabhiram — APPROVED** [review]

**Pull request merged**
