### PR TITLE
Ignore PLIC spurious interrupts in RISC-V supervisor mode

### PR DESCRIPTION
**Pull request by berendo**
This PR is a workaround for a currently-unexplained spurious interrupt that occurs during the initial IPC exchanges that take place between the SCPU, OCPU and the MIPI RX complexes as they are put into "tight loop" mode. The workaround is active only if RISC-V supervisor mode is enabled (i.e. MMU support) and simply ignores spurious interrupts (only `0`, not beyond the configured `PLIC_IRQS`).

### CODE REVIEW

**Review by sabhiram — APPROVED** [review]
🙏

**Review by brudley — APPROVED** [review]
Out of curiousity, do you have any idea of the frequenecy of these spurious ints?

**Comment by sabhiram** [comment]
There is a play-by-play in #dev-borg @brudley

**Comment by berendo** [comment]
> Out of curiousity, do you have any idea of the frequenecy of these spurious ints?

I want to make it clear - this is not a _general_ "spurious interrupt" problem. I have run stress tests of both the SCPU and the OCPU running in supervisor mode (with the MMU enabled) and generated IPC stress along with `ping` floods, etc.

The as-of-yet-unexplained issue is _specific_ to the IPC messages that are exchanged (ironically, while the system is pretty idle).

That said, the issue (exhibited as the OCPU throwing a "spurious interrupt" exception) occurs once out of approximately 25 resets of the system while the sensors are initialized and MIPI RX is told via IPC to go into its "tight loop" mode.

**Pull request merged**
