### PR TITLE
json: Skip unknown fields on parsing

### PR DESCRIPTION
**Pull request by trojahner**
Skip child objects and arrays that are not specified in the given object descriptor when parsing a JSON input string.
This patch adds support for extra child arrays which previously were not supported by the parser as opposed to additional child objects.

Copied from: https://github.com/zephyrproject-rtos/zephyr/pull/47989

### CODE REVIEW

**Comment by trojahner** [comment]
This should fix the "graph hydration error" when FW is confronted with a `meta` file with new fields in it.

**Comment by tdakhran** [comment]
The compilation fails with
```
/data/git/scorpio-fw/zephyr/lib/os/json.c:395:67: error: 'JSON_TOK_ARRAY_START' undeclared (first use in this function); did you mean 'JSON_TOK_LIST_START'?
  395 |  if (kv->value.type == JSON_TOK_OBJECT_START || kv->value.type == JSON_TOK_ARRAY_START) {
      |                                                                   ^~~~~~~~~~~~~~~~~~~~
      |                                                                   JSON_TOK_LIST_START
/data/git/scorpio-fw/zephyr/lib/os/json.c:395:67: note: each undeclared identifier is reported only once for each function it appears in
/data/git/scorpio-fw/zephyr/lib/os/json.c:396:46: error: 'struct json_obj' has no member named 'lex'; did you mean 'lexer'?
  396 |   while (field_count > 0 && lexer_next(&obj->lex, &kv->value)) {
      |                                              ^~~
      |                                              lexer
/data/git/scorpio-fw/zephyr/lib/os/json.c:403:9: error: 'JSON_TOK_ARRAY_END' undeclared (first use in this function); did you mean 'JSON_TOK_LIST_END'?
  403 |    case JSON_TOK_ARRAY_END:
      |         ^~~~~~~~~~~~~~~~~~
      |         JSON_TOK_LIST_END
````

**Comment by berendo** [comment]
If we intend to do this, we need to open a PR that's clearly identified as a "back port" PR (see, for example, #73) and as much as possible, `git cherry-pick` the changes rather than "copying" them. If this draft PR reaches a usable state, I would be happy to assist with that finalization.

**Comment by trojahner** [comment]
I fixed the compilation issues and confirm that this works now. @berendo I would appreciate if you could assist with bringing this into the form you imagine. Only a few names had to be changed from the original commit.

**Comment by berendo** [comment]
> Only a few names had to be changed from the original commit.

Yup, please give me an hour or so to sync our fork with the upstream, so that the commit that merged the PR we are "copying" is in our history and we can just `git cherry-pick` it (with minimal modifications).

**Comment by berendo** [comment]
Closed in lieu of #81 - thank you for digging this up and testing it @trojahner.

**Pull request closed without merging**
